name: Event Filters
on:
  push:
    branches:
      - dev
      - 'release/*'
    paths-ignore:
      - 'docs/**'
jobs:
  echo:
    name: Event Filter
    runs-on: ubuntu-latest
    steps:
      - name: Filtering event
        run: echo "Event filters working! Triggered on ${{ github.ref_name }} branch"